### ISSUE TITLE
FindMySQL.cmake Module Cannot Find Correct Library in Windows

### ISSUE THREAD

**Issue by fang-d** [julp/CMakeXFind#2]
Please forgive me for my poor English.

I have installed MySQL 8.0 and MinGW-w64 in Windows 10. I tried to use the FindMySQL.cmake file to link MySQL C API like this:

```cmake
SET (CMAKE_CXX_STANDARD 17)
SET (EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/bin)
SET (CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR})
FIND_PACKAGE (MySQL REQUIRED)
AUX_SOURCE_DIRECTORY (src DIR_SRCS)
ADD_EXECUTABLE (${PROJECT_NAME} ${DIR_SRCS})
INCLUDE_DIRECTORIES (
	${PROJECT_SOURCE_DIR}/headers
	${MYSQL_INCLUDE_DIRS}
)
TARGET_LINK_LIBRARIES (${PROJECT_NAME} ${MYSQL_LIBRARIES})
```

But it didn't work. So I modified FindMySQL.cmake from line 110 to line 135 like this:

```cmake
if(WIN32)   # MSVC
    include(SelectLibraryConfigurations)
    # "On Windows, the static library is mysqlclient.lib and the dynamic library is libmysql.dll. Windows distributions also include libmysql.lib, a static import library needed for using the dynamic library."
    #set(${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_DEBUG_NAMES "mysqld mysqlclientd")
    #set(${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_RELEASE_NAMES "mysql mysqlclient")
    set(${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_DEBUG_NAMES "mysql")
    set(${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_RELEASE_NAMES "mysql")
    
    find_library(
        ${MYSQL_PUBLIC_VAR_NS}_LIBRARY_RELEASE
        NAMES ${${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_RELEASE_NAMES}
        DOC "Release library for mysqlclient"
    )
    find_library(
        ${MYSQL_PUBLIC_VAR_NS}_LIBRARY_DEBUG
        NAMES ${${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_DEBUG_NAMES}
        DOC "Debug library for mysqlclient"
    )

    select_library_configurations("${MYSQL_PUBLIC_VAR_NS}")
else(WIN32) # MSVC
    # "On Unix (and Unix-like) sytems, the static library is libmysqlclient.a. The dynamic library is libmysqlclient.so on most Unix systems and libmysqlclient.dylib on OS X."
    find_library(
        ${MYSQL_PUBLIC_VAR_NS}_LIBRARY
        NAMES mysqlclient
        PATHS ${${PC_MYSQL_PRIVATE_VAR_NS}_LIBRARY_DIRS} ${${MYSQL_PUBLIC_VAR_NS}_MYSQL_CONFIG_LIBRARY_DIR}
    )
endif(WIN32)    # MSVC
```
and it worked well. I guess that it is because of the version of MySQL that caused this problem.

I think CMakeXFind is a fantastic project and I hope it will be better in the future.

Best wishes.

**Comment by julp** [comment]
Hi,

`${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_DEBUG_NAMES` should be different to `${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_RELEASE_NAMES`.

Can't you make it work by changing:
```cmake
    find_library(
        ${MYSQL_PUBLIC_VAR_NS}_LIBRARY
        NAMES mysqlclient
        PATHS ${${PC_MYSQL_PRIVATE_VAR_NS}_LIBRARY_DIRS} ${${MYSQL_PUBLIC_VAR_NS}_MYSQL_CONFIG_LIBRARY_DIR}
    )
```
Into:
```cmake
    find_library(
        ${MYSQL_PUBLIC_VAR_NS}_LIBRARY
        NAMES mysqlclient mysql # <= the line to modify
        PATHS ${${PC_MYSQL_PRIVATE_VAR_NS}_LIBRARY_DIRS} ${${MYSQL_PUBLIC_VAR_NS}_MYSQL_CONFIG_LIBRARY_DIR}
    )
```
?

The `if` part is really intended for *MSVC* or, at least, any environment where you have a different library to link to, according to the build type (release vs debug).

**Comment by fang-d** [comment]
Thank you for your replying, but it doesn't seem to work. I modified _FindMySQL.cmake_ from line 110 to line 135:
```cmake
if(MSVC)
    include(SelectLibraryConfigurations)
    # "On Windows, the static library is mysqlclient.lib and the dynamic library is libmysql.dll. Windows distributions also include libmysql.lib, a static import library needed for using the dynamic library."
    set(${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_DEBUG_NAMES "mysqld mysqlclientd")
    set(${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_RELEASE_NAMES "mysql mysqlclient")

    find_library(
        ${MYSQL_PUBLIC_VAR_NS}_LIBRARY_RELEASE
        NAMES ${${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_RELEASE_NAMES}
        DOC "Release library for mysqlclient"
    )
    find_library(
        ${MYSQL_PUBLIC_VAR_NS}_LIBRARY_DEBUG
        NAMES ${${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_DEBUG_NAMES}
        DOC "Debug library for mysqlclient"
    )

    select_library_configurations("${MYSQL_PUBLIC_VAR_NS}")
else(MSVC)
    # "On Unix (and Unix-like) sytems, the static library is libmysqlclient.a. The dynamic library is libmysqlclient.so on most Unix systems and libmysqlclient.dylib on OS X."
    find_library(
        ${MYSQL_PUBLIC_VAR_NS}_LIBRARY
        NAMES mysqlclient mysql # <= the line to modify
        PATHS ${${PC_MYSQL_PRIVATE_VAR_NS}_LIBRARY_DIRS} ${${MYSQL_PUBLIC_VAR_NS}_MYSQL_CONFIG_LIBRARY_DIR}
    )
endif(MSVC)
```
but neither MinGW nor MSVC could not work well. The _mingw32-make_ could build C++ object files after using `cmake -G "MinGW Makefiles" ..`, but it could not link them. I also tried `cmake -G "Visual Studio 16 2019" ..` and `cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" ..`, but CMake could not find the MySQL C API library and told me that:
```
Could NOT find MYSQL (missing: MYSQL_LIBRARY) (found version "8.0.19")
```
. As for Linux, it worked well in my Ubuntu Server 19.04 for Raspberry Pi where GCC 9.2 was installed.

I am looking forward to your reply.

**Comment by julp** [comment]
Hi,

thanks for the feedback.

What is the path of your mysql(client) library? (some options like `PATH_SUFFIXES` might be needed)

In your case, the `mysql_config` program, which could help, seems not to be found or doesn't exist and/or the output of `mysql_config --variable=pkglibdir` is "incorrect".

There is still a weird thing to me: what ever you pass in `if` or `else` part from those lines, `find_library` should consider the exact same paths so if you initially could find mysql with your changes, you should still be able to do so with mine.

**Comment by fang-d** [comment]
Thanks for your advice. I don't know whether `mysql_config` is needed by _FindMySQL.cmake_. I am sure that the `mysql_config` tool was not installed when I installed MySQL in `C:\Program Files\MySQL\MySQL Server 8.0\` while it was installed in Linux by default. Actually, I used to be curious about that.

I noticed your latest commit and tried it. However, I failed. Then, I tried to modified it the way I did first, and it works as before. I found that _FindMySQL.cmake_ could find my MySQL Path (as it could told me the version of MySQL correctly), but could not find the C API.

I have the same doubts as you. But what puzzled me most was that it could find the correct library when I used MinGW-w64, while MSVC could not.

PS. The following is the folder where my MySQL Server lies.
```
C:/Program Files/MySQL/MySQL Server 8.0
├─bin
├─docs
├─etc
├─include   // Headers of MySQL C API
│  ├─mysql
│  └─openssl
├─lib       // Libraries of MySQL C API
│  ├─mecab
│  │  ├─dic
│  │  │  ├─ipadic_euc-jp
│  │  │  ├─ipadic_sjis
│  │  │  └─ipadic_utf-8
│  │  └─etc
│  └─plugin
└─share
    ├─bulgarian
    ├─charsets
    ├─czech
    ├─danish
    ├─dutch
    ├─english
    ├─estonian
    ├─french
    ├─german
    ├─greek
    ├─hungarian
    ├─italian
    ├─japanese
    ├─korean
    ├─norwegian
    ├─norwegian-ny
    ├─polish
    ├─portuguese
    ├─romanian
    ├─russian
    ├─serbian
    ├─slovak
    ├─spanish
    ├─swedish
    └─ukrainian
```

**Comment by julp** [comment]
To give you some background:

In fact, I check for the tools `pkg-config` and `mysql_config`, if available and found, to reinject their informations as "hints" for `find_path` and `find_library`. They [both `pkg-config` and `mysql_config`] are not mandatory but they can provide useful information specialy if the library is installed in a non-standard location.

> I found that FindMySQL.cmake could find my MySQL Path (as it could told me the version of MySQL correctly), but could not find the C API.

Since you don't have these tools, MySQL's version was successfully extracted from mysql_version.h so it was indeed able to find this header but not the library.

I'll try to do some tests on my side.

**Comment by fang-d** [comment]
Thank you very much, and I will stay focus on this project.

**Comment by julp** [comment]
Hi,

my apologies, you were right. Could you please try the following:
```cmake
if(WIN32)
    include(SelectLibraryConfigurations)
    # "On Windows, the static library is mysqlclient.lib and the dynamic library is libmysql.dll. Windows distributions also include libmysql.lib, a static import library needed for using the dynamic library."
    set(${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_NAMES mysql mysqlclient)

    find_library(
        ${MYSQL_PUBLIC_VAR_NS}_LIBRARY_RELEASE
        NAMES ${${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_NAMES}
        DOC "Release library for mysqlclient"
        ${${MYSQL_PRIVATE_VAR_NS}_COMMON_FIND_OPTIONS}
    )
    # "Windows distributions also include a set of debug libraries. These have the same names as the nondebug libraries, but are located in the lib/debug library. You must use the debug libraries when compiling clients built using the debug C runtime."
    find_library(
        ${MYSQL_PUBLIC_VAR_NS}_LIBRARY_DEBUG
        NAMES ${${MYSQL_PRIVATE_VAR_NS}_POSSIBLE_NAMES}
        PATH_SUFFIXES debug
        DOC "Debug library for mysqlclient"
        ${${MYSQL_PRIVATE_VAR_NS}_COMMON_FIND_OPTIONS}
    )

    select_library_configurations("${MYSQL_PUBLIC_VAR_NS}")
else(WIN32)
    # "On Unix (and Unix-like) sytems, the static library is libmysqlclient.a. The dynamic library is libmysqlclient.so on most Unix systems and libmysqlclient.dylib on OS X."
    find_library(
        ${MYSQL_PUBLIC_VAR_NS}_LIBRARY
        NAMES mysqlclient mysql
        PATHS ${${MYSQL_PUBLIC_VAR_NS}_MYSQL_CONFIG_LIBRARY_DIR}
        ${${MYSQL_PRIVATE_VAR_NS}_COMMON_FIND_OPTIONS}
    )
endif(WIN32)
```

I've done several mistakes:
* it makes indeed more sense to apply the debug/release logic to Windows (WIN32), not only MSVC
* handling of debug libraries was incorrect ([there is no mysqld nor mysqlclientd libraries for debugging](https://dev.mysql.com/doc/refman/5.7/en/c-api-implementations.html))
* the lists for `*_POSSIBLE_*_NAMES` were malformed (this shouldn't be "name1 name2" but "name1" "name2" - this is not the same thing to CMake)

Thanks for your support.

**Comment by fang-d** [comment]
Brilliant! I tried it in my Winodws, and both MSVC and MinGW worked correctly! Thank you so much!
